export const hugeToolsList = [
  "Figma",
  "Adobe Photoshop",
  "Procreate",
  "Sketch",
  "Illustrator",
  "Adobe XD",
  "InVision",
  "Canva",
  "Affinity Designer",
  "CorelDRAW",
  "GIMP",
  "Inkscape",
  "Blender",
  "Adobe After Effects",
  "Cinema 4D",
  "Corel Painter",
  "Krita",
  "Gravit Designer",
  "Adobe Premiere Pro",
  "Marvel",
  "Zeplin",
  "Adobe InDesign",
  "Affinity Photo",
  "Autodesk Maya",
  "ZBrush",
  "Substance Painter",
  "Adobe Animate",
  "Clip Studio Paint",
  "PaintTool SAI",
  "Trello",
  "Miro",
  "Framer",
  "Principle",
  "DaVinci Resolve",
  "Final Cut Pro",
  "Houdini",
  "Adobe Lightroom",
  "SketchUp",
  "Vectorworks",
  "ArtRage",
  "MediBang Paint",
  "Affinity Publisher",
  "Lunacy",
  "Gravit Designer",
  "Fusion 360",
  "3ds Max",
  "V-Ray",
  "KeyShot",
  "Notion",
  "Asana",
  "Adobe Dimension",
  "Spark AR Studio",
  "Paint.NET",
  "Rebelle",
  "Marmoset Toolbag",
  "Unreal Engine",
  "Unity",
  "Photopea",
  "Pixlr",
  "Storyboarder",
]

export const hugeProjectTypes = [
  "Client Work",
  "Personal Project",
  "Freelance",
  "Experiment",
  "Branding",
  "UI/UX Design",
  "Web Development",
  "Mobile App Development",
  "Graphic Design",
  "Illustration",
  "Motion Graphics",
  "3D Modeling",
  "Animation",
  "Game Development",
  "Prototyping",
  "Product Design",
  "Packaging Design",
  "Editorial Design",
  "Advertising Campaign",
  "Social Media Content",
  "Logo Design",
  "Icon Design",
  "Typography Project",
  "Data Visualization",
  "Augmented Reality",
  "Virtual Reality",
  "E-commerce Platform",
  "Open Source Contribution",
  "Hackathon Project",
  "Startup MVP",
  "Art Installation",
  "Photography Series",
  "Video Editing",
  "Short Film",
  "Documentary",
  "Concept Art",
  "Character Design",
  "Environment Design",
  "User Research",
  "Wireframing",
  "Interaction Design",
  "Print Design",
  "Poster Design",
  "Infographic Creation",
  "NFT Creation",
  "Metaverse Experience",
  "Educational Content",
  "Portfolio Development",
  "Rebranding",
  "Event Branding",
  "Merchandise Design",
  "Interior Design Visualization",
  "Architectural Rendering",
  "Fashion Design",
  "Textile Design",
  "Game Asset Creation",
  "UI Component Library",
  "Design System",
  "Accessibility Audit",
  "Crowdfunding Campaign",
]
