export const search = [
  // General Design Terms
  "design",
  "graphic design",
  "ui design",
  "ux design",
  "user interface",
  "user experience",
  "web design",
  "mobile design",
  "app design",
  "interface design",
  "visual design",
  "digital design",
  "creative design",
  "modern design",
  "minimalist design",
  "flat design",
  "material design",
  "responsive design",
  "adaptive design",
  "interactive design",

  // UI/UX Specific
  "ui kit",
  "ux flow",
  "wireframe",
  "prototype",
  "mockup",
  "user flow",
  "design system",
  "component library",
  "style guide",
  "typography",
  "color palette",
  "accessibility",
  "a11y",
  "user testing",
  "interaction design",
  "microinteractions",
  "dashboard design",
  "landing page",
  "homepage design",
  "mobile app ui",

  // Design Styles
  "minimal",
  "modern",
  "retro",
  "vintage",
  "futuristic",
  "brutalist",
  "neomorphic",
  "glassmorphism",
  "skeuomorphic",
  "clean design",
  "bold design",
  "colorful design",
  "monochrome",
  "gradient design",
  "dark mode",
  "light mode",
  "3d design",
  "isometric design",
  "flat illustration",
  "hand-drawn",

  // Tools and Software
  "figma",
  "sketch",
  "adobe xd",
  "photoshop",
  "illustrator",
  "invision",
  "framer",
  "canva",
  "procreate",
  "after effects",
  "blender",
  "cinema 4d",
  "webflow",
  "wordpress",
  "elementor",
  "figma prototype",
  "adobe creative cloud",
  "uxpin",
  "axure",
  "miro",

  // Industries and Applications
  "ecommerce",
  "portfolio",
  "blog design",
  "saas",
  "fintech",
  "healthcare",
  "education",
  "travel",
  "food delivery",
  "social media",
  "gaming",
  "fitness app",
  "music app",
  "finance app",
  "real estate",
  "dashboard",
  "crm",
  "erp",
  "booking app",
  "event app",

  // Design Elements
  "button design",
  "card design",
  "form design",
  "navigation",
  "menu design",
  "sidebar",
  "footer design",
  "header design",
  "carousel",
  "slider",
  "modal",
  "popup",
  "tooltip",
  "icon design",
  "illustration",
  "vector art",
  "animation",
  "motion design",
  "logo design",
  "branding",

  // Colors
  "blue design",
  "red design",
  "green design",
  "purple design",
  "minimal white",
  "black and white",
  "pastel colors",
  "vibrant colors",
  "gradient",
  "monochromatic",
  "neon",
  "earthy tones",
  "muted colors",
  "bold colors",
  "soft colors",

  // Device and Platform
  "mobile",
  "desktop",
  "tablet",
  "ios",
  "android",
  "cross-platform",
  "responsive",
  "mobile-first",
  "web app",
  "native app",
  "hybrid app",
  "smartwatch",
  "vr design",
  "ar design",
  "wearable",

  // Trends and Concepts
  "dark theme",
  "light theme",
  "neumorphism",
  "glass effect",
  "microanimation",
  "parallax",
  "scroll animation",
  "3d illustration",
  "low poly",
  "pixel art",
  "cyberpunk",
  "retro wave",
  "vaporwave",
  "metaverse",
  "augmented reality",
  "virtual reality",
  "gamification",
  "voice ui",
  "chatbot ui",
  "ai design",

  // Specific Features
  "search bar",
  "filter design",
  "sorting",
  "pagination",
  "infinite scroll",
  "onboarding",
  "signup flow",
  "login page",
  "checkout",
  "payment ui",
  "profile page",
  "settings page",
  "analytics dashboard",
  "data visualization",
  "chart design",
  "graph design",
  "map interface",
  "calendar ui",
  "timeline",
  "notification",

  // Miscellaneous
  "portfolio website",
  "creative portfolio",
  "design inspiration",
  "trending designs",
  "popular designs",
  "community designs",
  "freelance design",
  "agency design",
  "startup design",
  "enterprise ui",
  "minimalist portfolio",
  "animated ui",
  "responsive layout",
  "grid layout",
  "flexbox design",
  "css animation",
  "svg animation",
  "design portfolio",
  "creative agency",
  "digital art",
]
