import type {Metadata} from "next"
import "./globals.css"
import Navbar from "@/components/Navbar"
import Providers from "./provider"

import {Poppins} from "next/font/google"

import AuthInitilizer from "@/components/protectedRoutes/AuthInitilizer"
import LoginPopup from "@/components/login/LoginPopup"
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// })
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// })
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100..900&display=swap"
          rel="stylesheet"
        /> */}
      </head>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AuthInitilizer>
            <div>
              <LoginPopup></LoginPopup>
              <Navbar></Navbar>
              <main className={poppins.className}>{children}</main>
              {/* <Footer></Footer> */}
              {/* <Test></Test> */}
            </div>
          </AuthInitilizer>
        </Providers>
      </body>
    </html>
  )
}
