import type {Metadata} from "next"
import {Poppins} from "next/font/google"
import Providers from "./provider"
import Navbar from "@/components/Navbar"
import AuthInitilizer from "@/components/protectedRoutes/AuthInitilizer"
import LoginPopup from "@/components/login/LoginPopup"
import "./globals.css"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthInitilizer>
            <div>
              <LoginPopup />
              <Navbar />
              <main className={poppins.className}>{children}</main>
            </div>
          </AuthInitilizer>
        </Providers>
      </body>
    </html>
  )
}
