export const dribbbleTags = [
  // Design Style
  "ui",
  "ux",
  "ui/ux",
  "user interface",
  "user experience",
  "illustration",
  "logo",
  "branding",
  "web design",
  "website",
  "mobile app",
  "app design",
  "dashboard",
  "landing page",
  "product design",
  "wireframe",
  "typography",
  "animation",
  "3d",
  "isometric",
  "minimal",
  "flat design",
  "clean design",
  "modern",
  "futuristic",
  "skeuomorphic",
  "microcopy",
  "design system",
  "visual design",
  "art direction",
  "style guide",
  "branding kit",
  "email design",
  "poster design",
  "flyer design",
  "banner design",
  "presentation design",
  "infographic",
  "icon design",

  // Platform
  "ios",
  "android",
  "responsive",
  "desktop",
  "mobile",
  "smartwatch",
  "tablet",
  "wearables",
  "vr design",
  "ar design",
  "tv app design",

  // Industry
  "e-commerce",
  "fintech",
  "saas",
  "crypto",
  "real estate",
  "education",
  "healthcare",
  "fitness",
  "food delivery",
  "travel",
  "finance",
  "social media",
  "fashion",
  "entertainment",
  "music",
  "gaming",
  "sports",
  "news",
  "dating app",

  // Color and Feel
  "colorful",
  "vibrant",
  "dark mode",
  "light mode",
  "pastel",
  "bold",
  "gradient",
  "soft ui",
  "glassmorphism",
  "neumorphism",
  "claymorphism",
  "high contrast",
  "monochrome",
  "vintage",
  "retro",
  "neon",

  // Technical Tools
  "figma",
  "adobe xd",
  "sketch",
  "photoshop",
  "after effects",
  "framer",
  "webflow",
  "blender",
  "cinema 4d",
  "adobe illustrator",
  "procreate",
  "affinity designer",
  "invision",
  "zeplin",
  "principle",

  // Other Creative
  "concept",
  "prototype",
  "case study",
  "redesign",
  "creative",
  "inspiration",
  "portfolio",
  "dribbble shot",
  "trending",
  "behance",
  "interaction",
  "microinteraction",
  "motion design",
  "loading animation",
  "scroll animation",
  "hover effect",
  "transition effect",
  "parallax",
  "scrolling website",
  "storytelling design",
  "minimalistic",
  "professional design",
  "startup design",
  "corporate design",
  "personal brand",
  "freelance designer",
]
